server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
  - job_name: api
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          app: fast-pin-pon-api
          __path__: /opt/logs/fast-pin-pon/*.log
  - job_name: keycloak
    static_configs:
      - targets:
          - localhost
        labels:
          job: keycloak
          app: fast-pin-pon-keycloak
          __path__: /opt/logs/keycloak/*.log
  - job_name: simulation
    static_configs:
      - targets:
          - localhost
        labels:
          job: simulation
          app: fast-pin-pon-simulation
          __path__: /opt/logs/simulation/*.log*
    pipeline_stages:
      - json:
          expressions:
            level: level
            logger: logger_name
            thread: thread_name
      - labels:
          level:
          logger:
          thread:
  - job_name: engine
    static_configs:
      - targets:
          - localhost
        labels:
          job: engine
          app: fast-pin-pon-engine
          __path__: /opt/logs/engine/*.log*
    pipeline_stages:
      - json:
          expressions:
            level: level
            logger: logger_name
            thread: thread_name
      - labels:
          level:
          logger:
          thread:
