global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'keycloak'
    metrics_path: /metrics
    static_configs:
      - targets: ['fast-pin-pon-keycloak:9000', 'keycloak_web:9000']

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['fast-pin-pon-api:8080', 'api:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
