name: Build Front Docker Image

on:
  push:
    branches:
      - main
      - feat/map-v2

  pull_request:
    branches:
      - main
      - '**'
    paths:
      - 'front/**'
      - '.github/workflows/bp-front.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Front Docker Image
    uses: ./.github/workflows/build-and-push.yml
    with:
      folder: front
      push_event: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    secrets: inherit