name: Build Front Docker Image

on:
  push:
    branches:
      - main
      - feat/map-v2

  pull_request:
    branches:
      - main
      - '**'
    paths:
      - 'front/**'
      - '.github/workflows/bp-front.yml'
  workflow_dispatch:

jobs:
  build:
      name: Build Swagger Site
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: api
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

  call-build:
    uses: ./.github/workflows/build-and-push.yml
    with:
      folder: front
      push_event: ${{ github.event_name != 'pull_request' }}
